// Global shared constants for EduVerse

export const NAV_LINKS = [
  { to: "/", label: "Roadmaps", auth: false },
  { to: "/videos", label: "Videos", auth: false },
  { to: "/communities", label: "Communities", auth: true },
  { to: "/ai-tutor", label: "AI Tutor", auth: true },
];

export const ROLE_BASED_ROADMAPS = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Data Analyst",
  "AI Engineer",
  "Data Scientist",
  "Data Engineer",
  "Android Developer",
  "Machine Learning Engineer",
  "iOS Developer",
  "Blockchain Developer",
  "QA Engineer",
  "Software Architect",
  "Cyber Security",
  "UX Designer",
  "Technical Writer",
  "Game Developer",
  "Product Manager",
  "Engineering Manager",
  "Developer Relations",
];

export const SKILL_BASED_ROADMAPS = [
  "SQL",
  "Computer Science",
  "React",
  "Vue",
  "Angular",
  "JavaScript",
  "TypeScript",
  "Node.js",
  "Python",
  "System Design",
  "Java",
  "ASP.NET Core",
  "API Design",
  "Spring Boot",
  "Flutter",
  "C++",
  "Rust",
  "Go",
  "Design and Architecture",
  "GraphQL",
  "React Native",
  "Design System",
  "Prompt Engineering",
  "MongoDB",
  "Linux",
  "Kubernetes",
  "Docker",
  "AWS",
  "Terraform",
  "Data Structures & Algorithms",
  "Redis",
  "Git and GitHub",
  "PHP",
  "Next.js",
  "Kotlin",
  "HTML",
  "CSS",
  "Swift & Swift UI",
];

export const AI_TUTOR_SIDEBAR = [
  { id: "plan", label: "Plan", path: "/ai-tutor" },
  { id: "course", label: "Course", path: "/ai-tutor" },
  { id: "guide", label: "Guide", path: "/guide-generator" },
  { id: "roadmap", label: "Roadmap", path: "/roadmap-generator" },
  { id: "quiz", label: "Quiz", path: "/ai-tutor" },
  { id: "ask", label: "Ask AI Tutor", path: "/ai-tutor" },
  { id: "community", label: "Community", path: "/community" },
];


